#Program to run
program: 'train_ddp.py'
#Sweep search method: random, grid or bayes
method: 'random'

# Project this sweep is part of
project: 'example_project'
entity: 'nyrenw'

# Metric to optimize
metric:
  name: 'val_srmse'
  goal: 'minimize'

# Parameters search space
parameters:
  lr: 
    values: [0.0005]
  init_lr:
    values: [0.0000001]
  final_lr:
    values: [0.00001]
  hidden_channels:
    values: [150, 250, 300]
  num_layers:
    values: [2, 4, 8]
  num_timesteps:
    values: [1, 3]
  dropout:
    values: [0.025]
  num_workers:
    value: 3
  total_epochs:
    value: 10
  warmup_epochs:
    value: 3
  batch_size:
    values: [0, 150]
  Attention_mode:
    values: ['GAT', 'DenseGAT', 'GATv2', 'MoGAT', 'MoGATv2']
  heads: 
    values: [3]
  loss_function:
    values: ['mse_loss', 'sid', 'kl_div']
  with_fake_edges: 
    value: 0
  lr_ddp_scaling:
    value: 0
  batch_ddp_scaling:
    value: 1
  savitzkey_golay:
    values: [0, 1 2, 1, 2]
#  seed:
#    values: [42, 13, 7]